root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

cmd = "dlv exec --accept-multiclient --headless --listen=:2345 --api-version=2 ./tmp/main.exe"

[build]
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"  # Output binary
  full_bin = "dlv exec --accept-multiclient --headless --listen=:2345 --api-version=2 ./tmp/main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 50&& 
  send_interrupt = false
  stop_on_error = false
  args_bin = ["server"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
